// <auto-generated />
namespace WebBiblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SincronizarCambiosRecientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SincronizarCambiosRecientes));
        
        string IMigrationMetadata.Id
        {
            get { return "202505261737310_SincronizarCambiosRecientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
