// <auto-generated />
namespace WebBiblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ModeloPrestamoYConfiguracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModeloPrestamoYConfiguracion));
        
        string IMigrationMetadata.Id
        {
            get { return "202505241029256_ModeloPrestamoYConfiguracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
