// <auto-generated />
namespace WebBiblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Libro_Concurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Libro_Concurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "202505301857589_Libro_Concurrency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
